### ISSUE TITLE
不支持流式dataset

### ISSUE THREAD

**Issue by af-74413592** [THUDM/SwissArmyTransformer#138]
visualglm只有FewshotData，数据直接加载到内存中会爆掉，改成
large_dataset_streamed = load_dataset("json", data_files=path,split="train", streaming=True)
dataset = large_dataset_streamed.map(datapreprocess)
的形式后，发现也不支持流式dataset。

**Comment by 1049451037** [comment]
支持流式，只需要在训练脚本里传入参数`--iterable-dataset`

**Comment by af-74413592** [comment]
谢谢
