### ISSUE TITLE
How to load and initialize llama2 models downloaded from Huggingface

### ISSUE THREAD

**Issue by microhu** [THUDM/SwissArmyTransformer#143]
Does the sat lib support. llama2? I found the parameters are not initilalized when using lamma class to load the vicuna-7b-1.5 model by using from_pretrained func. 
Could you kiindly give an. example of using sat to load and init the official llama2 models ?

**Comment by 1049451037** [comment]
We support llama2 in sat. But I haven't uploaded the weights to cloud. You can use the scripts here to transform the model downloaded from huggingface to sat format: https://github.com/THUDM/SwissArmyTransformer/tree/main/examples/llama

**Comment by microhu** [comment]
> We support llama2 in sat. But I haven't uploaded the weights to cloud. You can use the scripts here to transform the model downloaded from huggingface to sat format: https://github.com/THUDM/SwissArmyTransformer/tree/main/examples/llama

got, thanks. I will try
