### ISSUE TITLE
FileLock - out of date?

### ISSUE THREAD

**Issue by taziksh** [THUDM/SwissArmyTransformer#144]
Using [CogVLM](https://github.com/THUDM/CogVLM), which has SAT as a dependency. Had to remove the mode parameter in the line below to get my code to run.

https://github.com/THUDM/SwissArmyTransformer/blob/3cf20b8d3135796b9787e5deb649914bb84564f9/sat/resources/download.py#L50

Is this out of date?

**Comment by 1049451037** [comment]
`pip install -U filelock`
