### ISSUE TITLE
请问如何使用hf加载icetk_glm_130B的tokenizer和GLM130B的模型？

### ISSUE THREAD

**Issue by Ajay-Wong** [THUDM/SwissArmyTransformer#145]

**Comment by 1049451037** [comment]
As I know, there is no huggingface support for GLM130B. Enjoy using it in SAT :)

**Comment by Ajay-Wong** [comment]
> As I know, there is no huggingface support for GLM130B. Enjoy using it in SAT :)
> 
> If there is any question, feel free to post here and I will fix it as soon as possible.

好的，谢谢，那再问下，chatglm6b与130b模型结构上除了多一些层和维度的差别？是不是可以使用chatglm6b的方式改下模型参数，直接加载130b的模型？

**Comment by 1049451037** [comment]
具体使用方法可以参考GLM130B的仓库：https://github.com/THUDM/GLM-130B

**Comment by Ajay-Wong** [comment]
> 具体使用方法可以参考GLM130B的仓库：https://github.com/THUDM/GLM-130B

谢谢，这个看到了，有没有什么资料是介绍130b与chatglm6b或者chatglm2-6b的有什么区别的？

**Comment by 1049451037** [comment]
模型代码都在这里，可以自行比较：https://github.com/THUDM/SwissArmyTransformer/tree/main/sat/model/official

每个模型代码都是100行左右，很容易对比。

**Comment by Ajay-Wong** [comment]
> 模型代码都在这里，可以自行比较：https://github.com/THUDM/SwissArmyTransformer/tree/main/sat/model/official
> 
> 每个模型代码都是100行左右，很容易对比。

thanks
