### ISSUE TITLE
转换llama3.1遇到问题

### ISSUE THREAD

**Issue by strivebfq** [THUDM/SwissArmyTransformer#181]
config = LlamaConfig.from_pretrained(prefix+model_type)

llama3.1的转换遇到问题，新的llama版本里面新增加了部分参数，应当如何调整

ValueError: `rope_scaling` must be a dictionary with with two fields, `type` and `factor`, got {'factor': 8.0, 'low_freq_factor': 1.0, 'high_freq_factor': 4.0, 'original_max_position_embeddings': 8192, 'rope_type': 'llama3'}

**Comment by 1049451037** [comment]
这个看起来是huggingface的报错，尝试升级huggingface transformers？

**Comment by strivebfq** [comment]
> 这个看起来是huggingface的报错，尝试升级huggingface transformers？
升级transformers-4.44.0后解决 感谢
