### ISSUE TITLE
Bad URL in SwissArmyTransformer/resources/urls.py

### ISSUE THREAD

**Issue by pierrefdz** [THUDM/SwissArmyTransformer#46]
Line 14 of SwissArmyTransformer/resources/urls.py
``` 'coglm': 'https://lfs.aminer.cn/misc/cogview/coglm.zip'```

should be:
```'coglm': 'https://lfs.aminer.cn/misc/cogview/cogview2/coglm.zip'```

**Comment by pierrefdz** [comment]
#47

**Comment by Sleepychord** [comment]
merged! Thank you and I will update the pypi
