### ISSUE TITLE
No module named localAttention

### ISSUE THREAD

**Issue by feihuzhang** [THUDM/SwissArmyTransformer#50]
Thanks for your nice work.
It seems the localAttention lib is missing.

https://github.com/THUDM/SwissArmyTransformer/blob/85d018259f42c4eaf38447adec94725ac478d2ce/SwissArmyTransformer/ops/local_attention_function.py#L5

Did you use this? https://github.com/zzd1992/Image-Local-Attention
But, I see there are some differences.

Thanks.

**Comment by Sleepychord** [comment]
please use 
```
git clone https://github.com/Sleepychord/Image-Local-Attention
cd Image-Local-Attention && python setup.py install
```
I forked the Zhendong's repo and change the implementation for speed up and more functions.
